### ISSUE TITLE
translation forms

### ISSUE THREAD

**Issue by gwenfranck** [cc-archive/wiki#44]
I noticed by the way that the forms to register the start of a translation (https://wiki.creativecommons.org/wiki/Form:CC0_Translation,  https://wiki.creativecommons.org/wiki/Form:4.0_Translation ) 
are not working anymore.

**Comment by peterspdx** [comment]
@sarahpearson Do you want to look at the form as we used to have it and see if it still makes sense? Should we will kill it, revise it, or just have @mattl just put it back up?

**Comment by sarahpearson** [comment]
@peterspdx I vote we kill it. Very few teams have used it in the past year, and I think we can easily get the information we need from teams before they start a translation through other means. 

The form was used to create the wiki page for each translation, but it was difficult for teams to update because of the template. I think we should find a new way for teams to chronicle their translation decisions publicly. If you are okay with that, I'll open a new ticket for us to discuss options for that.

**Comment by peterspdx** [comment]
Ok! Let's do it. Which, I think, means doing nothing and removing references to it on the various policies pages and elsewhere it may appear on the website. Thanks.

**Comment by sarahpearson** [comment]
Great! It seems the wiki is down at the moment (Mari already filed a ticket about that separately), but I'll make a to-do to remove references to the form on the wiki. Same re: new ticket for translation summary plans.

**Comment by mattl** [comment]
@sarahpearson wiki is back...
